version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: vroomgine_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_services
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
